### ISSUE TITLE
Pre-publish checklist

### ISSUE THREAD

**Issue by yuchi** [smclab/liferay-theme-hooks#1]
- [x] Add minor README.md to each hook
- [x] Rename the `prettier` command to `format`
- [x] Avoid using Windows-specifc names in the scripts (do not use `./node_modules/.bin/prettier.cmd` but simply `prettier`, for example)
- [x] `prettier` is missing from the `devDependencies` of the workspace
- [x] Remove `package-lock.json` files
